#!/usr/bin/with-contenv sh

if [ ! ${DATALOOP_SERVER} ] ; then
  DATALOOP_SERVER="https://agent.dataloop.io"
fi

echo "Starting presence detection"
exec /usr/bin/python \
     /opt/dataloop/embedded/bin/presence.py -a $DATALOOP_AGENT_KEY -u $DATALOOP_SERVER >> /var/log/dataloop/presence.log 2>&1
